config/routes.rb
Rails.application.routes.draw do

  resources :panels do
    resources :widgets do
      collection do
        get 'widget_partial'
      end
    end
  end

  root 'panels#index'

end

app/models/widget.rb
class Widget < ActiveRecord::Base
  validates_presence_of :name

  #FIXME validates this presence
  belongs_to :panel

  has_settings :data

  def self.widget_types
    [TableWidget,SonarWidget, AskbotWidget, UrlWidget]
  end

end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  before_action :set_panel
  before_action :set_widget, only: [:show, :edit, :update, :destroy]

  # GET /widgets
  # GET /widgets.json
  def index
    @widgets = @panel.widgets.paginate(:page => params[:page])
  end

  # GET /widgets/1
  # GET /widgets/1.json
  def show
  end

  # GET /widgets/new
  def new
    @widget = load_widget
  end

  # GET /widgets/1/edit
  def edit
  end

  # POST /widgets
  # POST /widgets.json
  def create
    @widget = load_widget(widget_params)
    @widget.panel = @panel

    respond_to do |format|
      if @widget.save
        format.html { redirect_to panel_widgets_path(@panel), notice: 'Widget was successfully created.' }
        format.json { render :show, status: :created, location: @widget }
      else
        format.html { render :new }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /widgets/1
  # PATCH/PUT /widgets/1.json
  def update
    respond_to do |format|
      if @widget.update(widget_params)
        format.html { redirect_to panel_widgets_path(@panel), notice: 'Widget was successfully created.' }
        format.json { render :show, status: :ok, location: @widget }
      else
        format.html { render :edit }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /widgets/1
  # DELETE /widgets/1.json
  def destroy
    @widget.destroy
    respond_to do |format|
      format.html { redirect_to panel_widgets_url(@panel), notice: 'Widget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def widget_partial
    @widget = load_widget
    respond_to do |format|
      format.js
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_panel
      @panel = Panel.find(params[:panel_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_widget
      @widget = @panel.widgets.find(params[:id])
    end

    def load_widget(parameters = {})
      klass = Widget.descendants.detect{|w| w.name == params[:type]}
      @widget = (klass || UrlWidget).new(parameters)
      @widget
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def widget_params
      params.require(:widget).permit(UrlWidget.permit)
    end
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/widgets/_askbot_widget_form.html.erb
<div class="field">
  <%= label_tag 'widget[uri]', t(:uri) %>
  <%=  AskbotWidget.base_uri %>
</div>

app/views/widgets/_form.html.erb
<% if @widget.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@widget.errors.count, "error") %> prohibited this widget from being saved:</h2>

    <ul>
    <% @widget.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="field">
  <%= label_tag 'widget[name]', t(:name)%>
  <%= text_field_tag 'widget[name]', @widget.name %>
</div>

<div id='partial_for_widget'>
<%= render :partial => partial_for_widget(@widget) + '_form' %>
</div>

<% if @widget.new_record? %>
  <div class="field">
    <%= label_tag 'type', t(:type) %>
    <%= select_tag 'type', options_for_select(Widget.widget_types.map{|a| [a.model_name.human, a.to_s]}, @widget.type), {:id => 'widget_type'} %>
  </div>
<% end %>

<div class="actions">
  <%= f.submit %>
</div>

app/views/widgets/_sonar_widget_form.html.erb
<div class="field">
  <%= label_tag 'widget[uri]', t(:uri) %>
  <%=  SonarWidget.base_uri %>
</div>

app/views/widgets/_table_widget_form.html.erb
<div class="field">
  <%= label_tag 'widget[uri]', t(:table) %>
</div>

app/views/widgets/_url_widget_form.html.erb
<div class="field">
  <%= label_tag 'widget[url]', t(:url) %>
  <%= text_field_tag 'widget[url]', @widget.url, size: 60 %>
</div>

app/views/widgets/_widget.html.erb
<li id="widget-<%= widget.id %>">
  <span><%= link_to widget_fullname(widget), panel_widget_path(panel, widget) %></td>
  <span><%= link_to t(:edit), edit_panel_widget_path(panel,widget) %></span>
  <span><%= link_to t(:remove), panel_widget_path(panel, widget), method: :delete, data: { confirm: t(:are_you_sure) } %></span>
</li>

app/views/widgets/edit.html.erb
<h1><%= t(:edit_widget) %></h1>

<%= form_for([@panel, @widget], :url => panel_widget_path(@panel, @widget.id), :method => :put) do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
<% end %>

<%= link_to t(:show), panel_widget_path(@panel, @widget) %> |
<%= link_to t(:back), panel_widgets_path(@panel)  %>

app/views/widgets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= t('list_widgets', panel_name: @panel.name) %>
  <%= link_to t(:action_new), new_panel_widget_path(@panel) %>
</h1>

<ul id='list-of-widgets'>
  <%= render :partial => 'widget', :locals => {:panel => @panel}, :collection => @widgets %>
</ul>

<%= will_paginate @widgets %>

app/views/widgets/new.html.erb
<h1><%= t(:widget_new) %> </h1>

<%= form_for([@panel, @widget], :url => panel_widgets_path(@panel, @widget)) do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
<% end %>

<%= link_to 'Back', panel_widgets_path(@panel) %>

app/views/widgets/show.html.erb
<p id="notice"><%= notice %></p>

<%= render :partial => 'panels/'+partial_for_widget(@widget), :locals => {:widget => @widget} %>

<%= link_to t(:edit), edit_panel_widget_path(@panel, @widget) %> |
<%= link_to t(:back), panel_widgets_path(@panel) %>